### ISSUE TITLE
Error trying to install

### ISSUE THREAD

**Issue by Sithdown** [avinassh/rockstar#1]
Error and traceback:

```
Downloading/unpacking rockstar
  Downloading rockstar-0.3-py2-none-any.whl
Downloading/unpacking gitpython==1.0.1 (from rockstar)
  Running setup.py (path:c:\users\adrin~1\appdata\local\temp\pip_build_Adrißn\gitpython\setup.py) egg_info for package gitpython
    W:\DEV\Python2X\lib\distutils\dist.py:267: UserWarning: Unknown distribution option: 'test_requirements'
      warnings.warn(msg)

    warning: no files found matching 'README'
Cleaning up...
Exception:
Traceback (most recent call last):
  File "W:\DEV\Python2X\lib\site-packages\pip\basecommand.py", line 122, in main
    status = self.run(options, args)
  File "W:\DEV\Python2X\lib\site-packages\pip\commands\install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "W:\DEV\Python2X\lib\site-packages\pip\req.py", line 1234, in prepare_files
    req_to_install.assert_source_matches_version()
  File "W:\DEV\Python2X\lib\site-packages\pip\req.py", line 464, in assert_source_matches_version
    % (display_path(self.source_dir), version, self))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 60: ordinal not in range(128)

Traceback (most recent call last):
  File "W:\DEV\Python2X\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "W:\DEV\Python2X\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "W:\DEV\Python2X\Scripts\pip.exe\__main__.py", line 9, in <module>
  File "W:\DEV\Python2X\lib\site-packages\pip\__init__.py", line 185, in main
    return command.main(cmd_args)
  File "W:\DEV\Python2X\lib\site-packages\pip\basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 75: ordinal not in range(128)
```

Running Python 2.7.9

**Comment by avinassh** [comment]
Hey it's Python 3 only.
