### ISSUE TITLE
Does not support Rasberry PI

### ISSUE THREAD

**Issue by duaneking** [avinassh/rockstar#14]
I laughed when I saw this and wondered if it ran on my raspberry pi; Tried this on a rasberry pi and the version it installs does not work. :(

pi@raspberrypi ~/github/rockstar/lol/rockstar/RockStar $ python3 **init**.py
Traceback (most recent call last):
  File "**init**.py", line 9, in <module>
    import click
  File "/usr/local/lib/python3.2/dist-packages/click/**init**.py", line 18, in <module>
    from .core import Context, BaseCommand, Command, MultiCommand, Group, \
  File "/usr/local/lib/python3.2/dist-packages/click/core.py", line 8, in <module>
    from .types import convert_type, IntRange, BOOL
  File "/usr/local/lib/python3.2/dist-packages/click/types.py", line 7, in <module>
    from .exceptions import BadParameter
  File "/usr/local/lib/python3.2/dist-packages/click/exceptions.py", line 2, in <module>
    from .utils import echo
  File "/usr/local/lib/python3.2/dist-packages/click/utils.py", line 301
    file.write(u'\n')
                   ^
SyntaxError: invalid syntax

**Comment by avinassh** [comment]
Rockstars code in Raspberry Pi all the time. This is unacceptable. 

update the Python please and try again.

**Comment by duaneking** [comment]
It would seem I have not updated the packages on the PI in a while ;)

apt-get update / apt-get upgrade done... and I am already using the most up to date python package available for my rasbperry pi and I still get this error ;)

pi@raspberrypi ~/github/rockstar/lol/rockstar/RockStar $ python --version
Python 2.7.3
pi@raspberrypi ~/github/rockstar/lol/rockstar/RockStar $ python3 --version
Python 3.2.3

Best I can find on the topic of the u'' syntax is https://docs.djangoproject.com/en/1.8/topics/python3/#unicode-literals

**Comment by avinassh** [comment]
Is your script name `init.py`? try renaming it to something else?

From the traceback, looks like issue is coming from `click` library. And I think `click` is for [above Python 3.2 versions](https://github.com/mitsuhiko/click/blob/master/.travis.yml#L5,#L6)

As of now, you could install Rockstar from pip and it's the older version.

**Comment by duaneking** [comment]
I can get it working on the PI in Python 2 if I remove click.. I just have to rewrite a few methods.

The version of Python3 on the PI is 3.2, but as the docs for RockStar say "Python3" I hoped that wouldn't be an issue.

**Comment by avinassh** [comment]
> but as the docs for RockStar say "Python3" I hoped that wouldn't be an issue.

Sorry, you are right :/ 

I will try to this on Python 3.2 and update here.
