### ISSUE TITLE
FileNotFoundError after using "rock_it_bro.make_me_a_rockstar()"

### ISSUE THREAD

**Issue by xingyuanbu** [avinassh/rockstar#55]
Hi:
I installed rockstar today by using "pip install rockstar". It succeed and I can see  the "rockstar" is in C:\Python34\Lib\site-packages now.

Then I run 

```
from rockstar import RockStar

rock_it_bro = RockStar(days=300)
rock_it_bro.make_me_a_rockstar()
```

in my python 3.4 command line.

First two lines work well , and I can print the rock_it_bro(<rockstar.RockStar.RockStar object at 0x01015870>). 
But the third lines makes some errors as follow:

```
>>> rock_it_bro
<rockstar.RockStar.RockStar object at 0x01015870>
>>> rock_it_bro.make_me_a_rockstar()
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\git\cmd.py", line 573, in execute
    **subprocess_kwargs
  File "C:\Python34\lib\subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "C:\Python34\lib\subprocess.py", line 1112, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python34\lib\site-packages\rockstar\RockStar.py", line 65, in make_me
_a_rockstar
    self.repo = git.Repo.init(self.repo_path)
  File "C:\Python34\lib\site-packages\git\repo\base.py", line 764, in init
    git.init(**kwargs)
  File "C:\Python34\lib\site-packages\git\cmd.py", line 440, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "C:\Python34\lib\site-packages\git\cmd.py", line 810, in _call_process
    return self.execute(make_call(), **_kwargs)
  File "C:\Python34\lib\site-packages\git\cmd.py", line 576, in execute
    raise GitCommandNotFound(str(err))
git.exc.GitCommandNotFound: The system cannot find the file specified.
>>>
```

How can I fix it? 
Thank you~

**Comment by avinassh** [comment]
You don't have git installed.
