### ISSUE TITLE
Launch rockstar

### ISSUE THREAD

**Issue by tolsadus** [avinassh/rockstar#72]
Traceback (most recent call last):
  File "/usr/local/bin/rockstar", line 9, in <module>
    load_entry_point('rockstar==0.5', 'console_scripts', 'rockstar')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 357, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2394, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2108, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/Library/Python/2.7/site-packages/rockstar/**init**.py", line 1, in <module>
    from .RockStar import RockStar
  File "/Library/Python/2.7/site-packages/rockstar/RockStar.py", line 11, in <module>
    import git
  File "/Library/Python/2.7/site-packages/git/**init**.py", line 6, in <module>
    from repository import Repository, InvalidRepositoryError
  File "/Library/Python/2.7/site-packages/git/repository.py", line 11, in <module>
    from objects import Commit
  File "/Library/Python/2.7/site-packages/git/objects/**init**.py", line 10, in <module>
    from .submodule import util as smutil
  File "/Library/Python/2.7/site-packages/git/objects/submodule/util.py", line 3, in <module>
    from git.config import GitConfigParser
ImportError: cannot import name GitConfigParser

Hello,

I've just install rockstar, but when I try to launch rockstar, i've got an error about a GitConfigParser ?

Any ideas ?

Max.

**Comment by ohnx** [comment]
Did you try creating a repository using `git init`?

It seems like that's the issue.

**Comment by tolsadus** [comment]
Yes.

» rockstar --days=300
And after that I've got this error... :(

**Comment by tolsadus** [comment]
Ok i've just reinstall gitpython with pip and reinstall it... fixed.

Thanks
