### ISSUE TITLE
Gives the following error when I run it in pycharm 

### ISSUE THREAD

**Issue by vaibhavsethia** [avinassh/rockstar#97]
/Users/irateleaf/PycharmProjects/Demo/venv/bin/python /Users/irateleaf/PycharmProjects/Demo/venv/LetsDoIt.py
Making you a Rockstar Programmer
Making you a Rockstar Programmer
Traceback (most recent call last):
  File "/Users/irateleaf/PycharmProjects/Demo/venv/lib/python3.7/site-packages/git/refs/symbolic.py", line 137, in _get_ref_info
    fp = open(join(repo.git_dir, ref_path), 'rt')
FileNotFoundError: [Errno 2] No such file or directory: '/Users/irateleaf/PycharmProjects/Demo/venv/.git/refs/heads/master'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/irateleaf/PycharmProjects/Demo/venv/lib/python3.7/site-packages/git/refs/symbolic.py", line 91, in _iter_packed_refs
    fp = open(cls._get_packed_refs_path(repo), 'rt')
FileNotFoundError: [Errno 2] No such file or directory: '/Users/irateleaf/PycharmProjects/Demo/venv/.git/packed-refs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/irateleaf/PycharmProjects/Demo/venv/lib/python3.7/site-packages/git/refs/symbolic.py", line 111, in _iter_packed_refs
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/irateleaf/PycharmProjects/Demo/venv/LetsDoIt.py", line 4, in <module>
    rock_it_bro.make_me_a_rockstar()
  File "/Users/irateleaf/PycharmProjects/Demo/venv/lib/python3.7/site-packages/rockstar/RockStar.py", line 85, in make_me_a_rockstar
    self._edit_and_commit(str(uuid.uuid1()), commit_date)
  File "/Users/irateleaf/PycharmProjects/Demo/venv/lib/python3.7/site-packages/rockstar/RockStar.py", line 65, in _edit_and_commit
    self.repo.index.commit(self._get_random_commit_message())
  File "/Users/irateleaf/PycharmProjects/Demo/venv/lib/python3.7/site-packages/git/index/base.py", line 924, in commit
    head, author=author, committer=committer)
  File "/Users/irateleaf/PycharmProjects/Demo/venv/lib/python3.7/site-packages/git/objects/commit.py", line 299, in create_from_tree
    parent_commits = [repo.head.commit]
  File "/Users/irateleaf/PycharmProjects/Demo/venv/lib/python3.7/site-packages/git/refs/symbolic.py", line 183, in _get_commit
    obj = self._get_object()
  File "/Users/irateleaf/PycharmProjects/Demo/venv/lib/python3.7/site-packages/git/refs/symbolic.py", line 176, in _get_object
    return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
  File "/Users/irateleaf/PycharmProjects/Demo/venv/lib/python3.7/site-packages/git/refs/symbolic.py", line 125, in dereference_recursive
    hexsha, ref_path = cls._get_ref_info(repo, ref_path)
  File "/Users/irateleaf/PycharmProjects/Demo/venv/lib/python3.7/site-packages/git/refs/symbolic.py", line 148, in _get_ref_info
    for sha, path in cls._iter_packed_refs(repo):
RuntimeError: generator raised StopIteration

Process finished with exit code 1

**Comment by avinassh** [comment]
not able to reproduce

**Comment by toonsevrin** [comment]
Easy to reproduce: Just run this in docker and you get the error, please reopen @avinassh @vaibhavsethia
```Dockerfile
FROM python:3
ADD rs.py /bin/
RUN pip install rockstar
WORKDIR "/bin"
CMD [ "python" , "./rs.py" ]
```

And the solution is:
```Dockerfile
FROM python:3
ADD rs.py /bin/
RUN pip install rockstar
RUN pip install -U git+http://github.com/gitpython-developers/GitPython.git
WORKDIR "/bin"
CMD [ "python" , "./rs.py" ]
```

**Comment by toonsevrin** [comment]
**Solution:**\
After 

```bash
pip install rockstar
```
run
```bash
pip install -U git+http://github.com/gitpython-developers/GitPython.git
```

Note that this installs the latest GitPython master (if you're a security freak you should specify a trusted version instead).
